### ISSUE TITLE
Reduce frequency of volcanoes / rework frequency logic

### ISSUE THREAD

**Issue by Cervator** [Terasology/Volcanoes#6]
`VolcanoProvider` at present has some test/live code that used to help toggle between lots of volcanoes and a more reasonable amount of volcanoes. Now that the module is stable we really should go back to the live frequency, but the old code there isn't working and might be better rewritten anyway.

On top of that there's a test world specific for volcanoes, so maybe the logic could be written in a way to prepare it for when world generator configurations work again, meaning you can pick the frequency in the main menu during game setup, then the default frequency could be something decent and the test world would increase the default dramatically

May be of interest to @sin3point14 or @4Denthusiast

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
